### ISSUE TITLE
Arcade - platform not found in igdb

### ISSUE THREAD

**Issue by daedric7** [zurdi15/romm#13]
Was attempting to scan my EmulatorJS library, and after Sega 32X got this error:

```
romm     | WARNING:  [ROMM] platform not found in igdb 2023-03-27 20:07:30
romm     | INFO:          [ROMM] filesystem roms found for sega32x: [] 2023-03-27 20:07:30
romm     | INFO:          [ROMM] filesystem roms found for sega32x: [] 2023-03-27 20:07:30
romm     | INFO:          [ROMM] Purge sega32x 2023-03-27 20:07:30
romm     | INFO:          [ROMM] filesystem roms found for sega32x: [] 2023-03-27 20:07:30
romm     | INFO:          [ROMM] Getting arcade details 2023-03-27 20:07:30
romm     | INFO:     10.0.2.4:0 - "PUT /scan?overwrite=false HTTP/1.0" 500 Internal Server Error
romm     | ERROR:    Exception in ASGI application
romm     | Traceback (most recent call last):
romm     |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
romm     |     result = await app(  # type: ignore[func-returns-value]
romm     |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
romm     |     return await self.app(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
romm     |     await super().__call__(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
romm     |     await self.middleware_stack(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
romm     |     raise exc
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
romm     |     await self.app(scope, receive, _send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
romm     |     await self.simple_response(scope, receive, send, request_headers=headers)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
romm     |     await self.app(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
romm     |     raise exc
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
romm     |     await self.app(scope, receive, sender)
romm     |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
romm     |     raise e
romm     |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
romm     |     await self.app(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
romm     |     await route.handle(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
romm     |     await self.app(scope, receive, send)
romm     |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
romm     |     response = await func(request)
romm     |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
romm     |     raw_response = await run_endpoint_function(
romm     |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
romm     |     return await dependant.call(**values)
romm     |   File "/back/./main.py", line 84, in scan
romm     |     p_igdb_id: str = fastapi.scan_platform(overwrite, p_slug, igdbh, dbh)
romm     |   File "/back/./utils/fastapi.py", line 24, in scan_platform
romm     |     p_igdb_id, p_name, url_logo = igdbh.get_platform_details(p_slug)
romm     |   File "/back/./handler/igdb_handler.py", line 26, in wrapper
romm     |     return func(*args)
romm     |   File "/back/./handler/igdb_handler.py", line 40, in get_platform_details
romm     |     id_logo = res_details['platform_logo']
romm     | KeyError: 'platform_logo'
```

Weird thing is, there are no arcade roms in the arcade/roms dir.

(Edited, i thought sega32x was causing the error, but it's what comes AFTEE sega32x)

**Comment by daedric7** [comment]
Worked arround it by removing the arcade folder from the scan dir.

**Comment by zurdi15** [comment]
I need to remove those "platform_logo" references because it is legacy code as I am not planning on using the platforms logos (the icons are stored inside the container, and if the platform does not have one or it does not exists in IGDB, it should appear the name of the folder and anything else in the platform selector). 

In any case, if a platform folder exists, with a rom folder inside even if the rom folder is empty it will appear in the selector. Maybe I should change that and omit the platform if it has no games inside

**Comment by zurdi15** [comment]
Just built the v1.1 with the platform logo issue fixed. Now you can have any platform with any name.
