### ISSUE TITLE
[Bug] Error when scanning library

### ISSUE THREAD

**Issue by PriorityPete** [zurdi15/romm#193]
**RomM version**
Latest

**Describe the bug**
When trying to scan for roms I'm getting an error and the following log output:

```
22.04.2023 13:34:23
INFO:     172.20.0.1:0 - "GET /platforms HTTP/1.0" 200 OK
22.04.2023 13:34:23
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:34:23
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:34:23
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:34:23
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:34:23
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:36:06
INFO:	  [RomM][2023-04-22 13:36:06] 🔎 Scanning 
22.04.2023 13:36:06
INFO:	  [RomM][2023-04-22 13:36:06] Platforms to be scanned: gb, gba, gbc, gc, n64, nds, nes, ps2, snes, wiiu, bios, @eaDir
22.04.2023 13:36:06
INFO:	  [RomM][2023-04-22 13:36:06] 🎮 gb 
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /scan?platforms=[]&full_scan=true HTTP/1.0" 500 Internal Server Error
22.04.2023 13:36:07
ERROR:    Exception in ASGI application
22.04.2023 13:36:07
Traceback (most recent call last):
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
22.04.2023 13:36:07
    result = await app(  # type: ignore[func-returns-value]
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
22.04.2023 13:36:07
    return await self.app(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 271, in __call__
22.04.2023 13:36:07
    await super().__call__(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 118, in __call__
22.04.2023 13:36:07
    await self.middleware_stack(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
22.04.2023 13:36:07
    raise exc
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
22.04.2023 13:36:07
    await self.app(scope, receive, _send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__
22.04.2023 13:36:07
    await self.app(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
22.04.2023 13:36:07
    raise exc
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
22.04.2023 13:36:07
    await self.app(scope, receive, sender)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
22.04.2023 13:36:07
    raise e
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
22.04.2023 13:36:07
    await self.app(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 706, in __call__
22.04.2023 13:36:07
    await route.handle(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
22.04.2023 13:36:07
    await self.app(scope, receive, send)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
22.04.2023 13:36:07
    response = await func(request)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
22.04.2023 13:36:07
    raw_response = await run_endpoint_function(
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 165, in run_endpoint_function
22.04.2023 13:36:07
    return await run_in_threadpool(dependant.call, **values)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
22.04.2023 13:36:07
    return await anyio.to_thread.run_sync(func, *args)
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
22.04.2023 13:36:07
    return await get_asynclib().run_sync_in_worker_thread(
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
22.04.2023 13:36:07
    return await future
22.04.2023 13:36:07
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
22.04.2023 13:36:07
    result = context.run(func, *args)
22.04.2023 13:36:07
  File "/back/./main.py", line 34, in scan
22.04.2023 13:36:07
    platform: Platform = fastapi.scan_platform(p_slug)
22.04.2023 13:36:07
  File "/back/./utils/fastapi.py", line 30, in scan_platform
22.04.2023 13:36:07
    platform_attrs['n_roms'] = fs.get_roms(p_slug, True, only_amount=True)
22.04.2023 13:36:07
  File "/back/./utils/fs.py", line 167, in get_roms
22.04.2023 13:36:07
    fs_single_roms: list[str] = list(os.walk(roms_path))[0][2]
22.04.2023 13:36:07
IndexError: list index out of range
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms HTTP/1.0" 200 OK
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
22.04.2023 13:36:07
INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
```

This is the full log when im freshly starting the container and then try to perform a full scan:

```
22.04.2023 13:56:53
    INFO:     [RomM][alembic.runtime.migration] Context impl SQLiteImpl.
    22.04.2023 13:56:53
    INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
    22.04.2023 13:56:54
    WARNING:  [RomM][2023-04-22 13:56:54] Twitch token invalid: fetching a new one
    22.04.2023 13:56:55
    INFO:	  [RomM][2023-04-22 13:56:55] Twitch token fetched!
    22.04.2023 13:56:55
    INFO:     Started server process [15]
    22.04.2023 13:56:55
    INFO:     Waiting for application startup.
    22.04.2023 13:56:55
    INFO:     Application startup complete.
    22.04.2023 13:56:55
    INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
    22.04.2023 13:57:05
    INFO:     172.20.0.1:0 - "GET /platforms HTTP/1.0" 200 OK
    22.04.2023 13:57:08
    INFO:	  [RomM][2023-04-22 13:57:08] 🔎 Scanning 
    22.04.2023 13:57:08
    INFO:	  [RomM][2023-04-22 13:57:08] Platforms to be scanned: gb, gba, gbc, gc, n64, nds, nes, ps2, snes, wiiu, bios, @eaDir
    22.04.2023 13:57:08
    INFO:	  [RomM][2023-04-22 13:57:08] 🎮 gb 
    22.04.2023 13:57:09
    INFO:     172.20.0.1:0 - "GET /scan?platforms=[]&full_scan=true HTTP/1.0" 500 Internal Server Error
    22.04.2023 13:57:09
    ERROR:    Exception in ASGI application
    22.04.2023 13:57:09
    Traceback (most recent call last):
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    22.04.2023 13:57:09
        raise exc
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    22.04.2023 13:57:09
        await self.app(scope, receive, _send)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    22.04.2023 13:57:09
        await self.app(scope, receive, send)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    22.04.2023 13:57:09
        raise exc
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    22.04.2023 13:57:09
        await self.app(scope, receive, sender)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    22.04.2023 13:57:09
        await self.app(scope, receive, send)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    22.04.2023 13:57:09
        response = await func(request)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
    22.04.2023 13:57:09
        raw_response = await run_endpoint_function(
    22.04.2023 13:57:09
        return await run_in_threadpool(dependant.call, **values)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    22.04.2023 13:57:09
        return await anyio.to_thread.run_sync(func, *args)
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 31, in run_sync
    22.04.2023 13:57:09
        return await get_asynclib().run_sync_in_worker_thread(
    22.04.2023 13:57:09
      File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    22.04.2023 13:57:09
    INFO:     172.20.0.1:0 - "GET /platforms HTTP/1.0" 200 OK
    22.04.2023 13:57:09
    INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
    22.04.2023 13:57:09
    INFO:     172.20.0.1:0 - "GET /platforms/undefined/roms HTTP/1.0" 200 OK
```

I'm not using mariadb. I used the synology docker interface to start the container, but the compose file would have looked something like this:

```
version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - CLIENT_ID=MY CLIENT ID
      - CLIENT_SECRET=MY CLIENT SECRET
      - STEAMGRIDDB_API_KEY=WIP
    volumes:
      - '/volume1/data/media/roms:/romm/library'
      - '/volume1/docker/romm/resource:/romm/resources'
      - '/volume1/docker/romm/config.yml:/romm/config.yml'
      - '/volume1/docker/romm/database:/romm/database' # Only if ROMM_DB_DRIVER='sqlite' or ROMM_DB_DRIVER not exists 
    ports:
      - '3020:80'
    depends_on:
      - romm_db
    restart: "unless-stopped"
```

My roms are all in /volume1/data/media/roms/ e.g. /volume1/data/media/roms/gbc.
The filetypes inside these folders range from .zips, .iso, .nds, etc.

**Comment by zurdi15** [comment]
Hello! You have the roms library binded wrong. You need to bind the ``parent`` folder of your ``roms`` folder.

e.g: 
```
volumes:
      - '/volume1/data/media:/romm/library'
```

In your case you could move your ``roms`` folder one folder deeper, something like ``/volume1/data/media/library/roms`` and then bind the ``library`` folder:

```
volumes:
      - '/volume1/data/media/library:/romm/library'
```

If you want to keep your current folder structure, then you need to add a ``roms`` folder inside each ``platform`` folder and put there your roms.

This is because RomM supports two different folder structures. For more information check the [folder structure](https://github.com/zurdi15/romm#-folder-structure) configuration

**Comment by PriorityPete** [comment]
You are right, changing the mount fixed my issue! Thank you 😄 .

Issue can be closed.
