### ISSUE TITLE
[Bug] problem starting container

### ISSUE THREAD

**Issue by victor10100111001** [zurdi15/romm#215]
**RomM version**
1.18.1
**Describe the bug**
When i start the container in docker desktop it switches status between "running" and "other". I am not able to access the web UI

**To Reproduce**
I am using this docker compose file:
```
version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - ROMM_DB_DRIVER="sqlite" # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - CLIENT_ID=[Redacted]
      - CLIENT_SECRET=[Redacted]
      - STEAMGRIDDB_API_KEY=WIP
    volumes:
      - 'C:\Users\victo\Desktop\Dockers\Romm\library:/romm/library'
      - 'C:\Users\victo\Desktop\Dockers\Romm\resources:/romm/resources'
      - 'C:\Users\victo\Desktop\Dockers\Romm\config.yml:/romm/config.yml'
      - 'C:\Users\victo\Desktop\Dockers\Romm\database:/romm/database' # Only if ROMM_DB_DRIVER='sqlite' or ROMM_DB_DRIVER not exists 
    ports:
      - '80:80'
    restart: "unless-stopped"
```

**Expected behavior**
I have noticed that when i haven't created a config.yml file the container creates a config.yml **directory**. I think this might have something to do with the problem. These are the logs i get:
```
2023-04-28 16:23:19 romm  | Traceback (most recent call last):
2023-04-28 16:23:19 romm  |   File "/usr/local/bin/alembic", line 8, in <module>
2023-04-28 16:23:19 romm  |     sys.exit(main())
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 591, in main
2023-04-28 16:23:19 romm  |     CommandLine(prog=prog).main(argv=argv)
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 585, in main
2023-04-28 16:23:19 romm  |     self.run_cmd(cfg, options)
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 562, in run_cmd
2023-04-28 16:23:19 romm  |     fn(
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 378, in upgrade
2023-04-28 16:23:19 romm  |     script.run_env()
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 576, in run_env
2023-04-28 16:23:19 romm  |     util.load_python_file(self.dir, "env.py")
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2023-04-28 16:23:19 romm  |     module = load_module_py(module_id, path)
2023-04-28 16:23:19 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2023-04-28 16:23:19 romm  |     spec.loader.exec_module(module)  # type: ignore
2023-04-28 16:23:19 romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-04-28 16:23:19 romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-04-28 16:23:19 romm  |   File "/back/alembic/env.py", line 8, in <module>
2023-04-28 16:23:19 romm  |     cl = ConfigLoader()
2023-04-28 16:23:19 romm  |   File "/back/./config/config_loader.py", line 18, in __init__
2023-04-28 16:23:19 romm  |     self._parse_config()
2023-04-28 16:23:19 romm  |   File "/back/./config/config_loader.py", line 49, in _parse_config
2023-04-28 16:23:19 romm  |     self.config['EXCLUDED_PLATFORMS'] = self.config['exclude']['platforms'] if self.config['exclude']['platforms'] else []
2023-04-28 16:23:19 romm  | TypeError: 'NoneType' object is not subscriptable
2023-04-28 16:23:21 romm  | Traceback (most recent call last):
2023-04-28 16:23:21 romm  |   File "/usr/local/bin/alembic", line 8, in <module>
2023-04-28 16:23:21 romm  |     sys.exit(main())
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 591, in main
2023-04-28 16:23:21 romm  |     CommandLine(prog=prog).main(argv=argv)
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 585, in main
2023-04-28 16:23:21 romm  |     self.run_cmd(cfg, options)
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 562, in run_cmd
2023-04-28 16:23:21 romm  |     fn(
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 378, in upgrade
2023-04-28 16:23:21 romm  |     script.run_env()
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 576, in run_env
2023-04-28 16:23:21 romm  |     util.load_python_file(self.dir, "env.py")
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2023-04-28 16:23:21 romm  |     module = load_module_py(module_id, path)
2023-04-28 16:23:21 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2023-04-28 16:23:21 romm  |     spec.loader.exec_module(module)  # type: ignore
2023-04-28 16:23:21 romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-04-28 16:23:21 romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-04-28 16:23:21 romm  |   File "/back/alembic/env.py", line 8, in <module>
2023-04-28 16:23:21 romm  |     cl = ConfigLoader()
2023-04-28 16:23:21 romm  |   File "/back/./config/config_loader.py", line 18, in __init__
2023-04-28 16:23:21 romm  |     self._parse_config()
2023-04-28 16:23:21 romm  |   File "/back/./config/config_loader.py", line 49, in _parse_config
2023-04-28 16:23:21 romm  |     self.config['EXCLUDED_PLATFORMS'] = self.config['exclude']['platforms'] if self.config['exclude']['platforms'] else []
2023-04-28 16:23:21 romm  | TypeError: 'NoneType' object is not subscriptable
2023-04-28 16:23:23 romm  | Traceback (most recent call last):
2023-04-28 16:23:23 romm  |   File "/usr/local/bin/alembic", line 8, in <module>
2023-04-28 16:23:23 romm  |     sys.exit(main())
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 591, in main
2023-04-28 16:23:23 romm  |     CommandLine(prog=prog).main(argv=argv)
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 585, in main
2023-04-28 16:23:23 romm  |     self.run_cmd(cfg, options)
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 562, in run_cmd
2023-04-28 16:23:23 romm  |     fn(
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 378, in upgrade
2023-04-28 16:23:23 romm  |     script.run_env()
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 576, in run_env
2023-04-28 16:23:23 romm  |     util.load_python_file(self.dir, "env.py")
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2023-04-28 16:23:23 romm  |     module = load_module_py(module_id, path)
2023-04-28 16:23:23 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2023-04-28 16:23:23 romm  |     spec.loader.exec_module(module)  # type: ignore
2023-04-28 16:23:23 romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-04-28 16:23:23 romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-04-28 16:23:23 romm  |   File "/back/alembic/env.py", line 8, in <module>
2023-04-28 16:23:23 romm  |     cl = ConfigLoader()
2023-04-28 16:23:23 romm  |   File "/back/./config/config_loader.py", line 18, in __init__
2023-04-28 16:23:23 romm  |     self._parse_config()
2023-04-28 16:23:23 romm  |   File "/back/./config/config_loader.py", line 49, in _parse_config
2023-04-28 16:23:23 romm  |     self.config['EXCLUDED_PLATFORMS'] = self.config['exclude']['platforms'] if self.config['exclude']['platforms'] else []
2023-04-28 16:23:23 romm  | TypeError: 'NoneType' object is not subscriptable
2023-04-28 16:23:25 romm  | Traceback (most recent call last):
2023-04-28 16:23:25 romm  |   File "/usr/local/bin/alembic", line 8, in <module>
2023-04-28 16:23:25 romm  |     sys.exit(main())
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 591, in main
2023-04-28 16:23:25 romm  |     CommandLine(prog=prog).main(argv=argv)
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 585, in main
2023-04-28 16:23:25 romm  |     self.run_cmd(cfg, options)
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 562, in run_cmd
2023-04-28 16:23:25 romm  |     fn(
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 378, in upgrade
2023-04-28 16:23:25 romm  |     script.run_env()
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 576, in run_env
2023-04-28 16:23:25 romm  |     util.load_python_file(self.dir, "env.py")
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2023-04-28 16:23:25 romm  |     module = load_module_py(module_id, path)
2023-04-28 16:23:25 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2023-04-28 16:23:25 romm  |     spec.loader.exec_module(module)  # type: ignore
2023-04-28 16:23:25 romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-04-28 16:23:25 romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-04-28 16:23:25 romm  |   File "/back/alembic/env.py", line 8, in <module>
2023-04-28 16:23:25 romm  |     cl = ConfigLoader()
2023-04-28 16:23:25 romm  |   File "/back/./config/config_loader.py", line 18, in __init__
2023-04-28 16:23:25 romm  |     self._parse_config()
2023-04-28 16:23:25 romm  |   File "/back/./config/config_loader.py", line 49, in _parse_config
2023-04-28 16:23:25 romm  |     self.config['EXCLUDED_PLATFORMS'] = self.config['exclude']['platforms'] if self.config['exclude']['platforms'] else []
2023-04-28 16:23:25 romm  | TypeError: 'NoneType' object is not subscriptable
2023-04-28 16:23:28 romm  | Traceback (most recent call last):
2023-04-28 16:23:28 romm  |   File "/usr/local/bin/alembic", line 8, in <module>
2023-04-28 16:23:28 romm  |     sys.exit(main())
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 591, in main
2023-04-28 16:23:28 romm  |     CommandLine(prog=prog).main(argv=argv)
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 585, in main
2023-04-28 16:23:28 romm  |     self.run_cmd(cfg, options)
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/config.py", line 562, in run_cmd
2023-04-28 16:23:28 romm  |     fn(
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/command.py", line 378, in upgrade
2023-04-28 16:23:28 romm  |     script.run_env()
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/script/base.py", line 576, in run_env
2023-04-28 16:23:28 romm  |     util.load_python_file(self.dir, "env.py")
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2023-04-28 16:23:28 romm  |     module = load_module_py(module_id, path)
2023-04-28 16:23:28 romm  |   File "/usr/local/lib/python3.10/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2023-04-28 16:23:28 romm  |     spec.loader.exec_module(module)  # type: ignore
2023-04-28 16:23:28 romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-04-28 16:23:28 romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-04-28 16:23:28 romm  |   File "/back/alembic/env.py", line 8, in <module>
2023-04-28 16:23:28 romm  |     cl = ConfigLoader()
2023-04-28 16:23:28 romm  |   File "/back/./config/config_loader.py", line 18, in __init__
2023-04-28 16:23:28 romm  |     self._parse_config()
2023-04-28 16:23:28 romm  |   File "/back/./config/config_loader.py", line 49, in _parse_config
2023-04-28 16:23:28 romm  |     self.config['EXCLUDED_PLATFORMS'] = self.config['exclude']['platforms'] if self.config['exclude']['platforms'] else []
2023-04-28 16:23:28 romm  | TypeError: 'NoneType' object is not subscriptable
1970-01-01 01:00:00 romm exited with code 1
1970-01-01 01:00:00 romm exited with code 0
1970-01-01 01:00:00 
```

**Desktop (please complete the following information):**
 I am using Windows 11

Thank you for creating this awesome software

**Comment by zurdi15** [comment]
Hi! Yes, indeed is a problem for no having a config.yml file. This is how docker works: if you bind a file to the container but that file doesn't exists in the host, docker will create a folder with that name.

I can improve RomM detecting it to and not to fail, but for now just create an empty config.yml file to avoid the error if you don't want to use the config options.

**Comment by victor10100111001** [comment]
I think i tried creating a config.yml file. In that case no folder was created, but it still failed. I am not currently at my computer so i cant test it again

**Comment by kampma** [comment]
Greetings! I'm having a similar issue.  Attempted to run `romm` on a Synology, Intel Atom quad-core.  All required directories and the `config.yml` file exist and have proper permissions.  I have tried with both `maria_db` and `sqlite` database options.  In both instances after running the container with `docker-compose`, the `romm` container exits with code 3. The database container `romm_db `(mariadb) starts just fine! I tried to determine what is causing this but I can't even view the log output from `docker-compose logs` as the container crashes immediately after starting.  The only output I have from container is `romm exited with code 3`. I have tried to restart romm with the romm_db container still running to see if was due to `romm` not connecting to the database.  Is there another way of viewing startup logs for the romm container?  Thanks in advance for the help!

**Comment by zurdi15** [comment]
Hi @victor10100111001  , could you manage to fix this?

**Comment by victor10100111001** [comment]
Unfortunately not. I have tried deleting the database and double checked my folder structure. Does it work for you and which os are you using?

**Comment by zurdi15** [comment]
I am deploying it in a raspbian with the docker-compose.yml editor of portainer and also deployed it directly with docker compose bare metal (without portainer).

**Comment by GAntoine** [comment]
@victor10100111001 Can you `exec` into the running container and see if the config file and library mounted correctly? Post the output of both commands here.

```sh
docker exec -it romm /bin/bash
ls -l /romm/library
cat /romm/config.yml
```

**Comment by victor10100111001** [comment]
@GAntoine  Sorry for the late response. I am unfortunately not able to exec into the container as i get this error: `Error response from daemon: Container c365a2c374cb66a0dba5d53d36b75e3d3d0c4059a370109b575d2a4c0249d441 is restarting, wait until the container is running`

This is what my folder structure looks like:

Romm/
├─ config/
├─ database/
├─ library/
│  ├─ roms/
│  │  ├─ 3ds/
│  │  │  ├─ rom1.3ds
│  │  ├─ gb/
│  │  │  ├─ rom2.gb 
│  │  ├─ nds/
│  │  │  ├─ rom3.nds
├─ config.yml
├─ docker-compose.yml
├─ resources/

**Comment by GAntoine** [comment]
Seems your container might be stuck in a boot loop, can you post the output of `docker ps`?

**Comment by GAntoine** [comment]
You've got a hung container, which you'll need to kill and remove, as well as any volumes. At this point we're outside the scope of the project itself; you may be able to find help among docker folks.
