### ISSUE TITLE
[Bug] Failure when renaming ROM to a name with a slash

### ISSUE THREAD

**Issue by ThibaultNocchi** [zurdi15/romm#348]
**RomM version**
Latest Docker image

**Describe the bug**
When renaming a ROM while identifying it, if the game has a slash in the name, then the rename and hence the identification fails. 

**To Reproduce**
1. Go to identify a game with a slash such as https://www.igdb.com/games/kingdom-hearts-358-2-days
2. Check Rename ROM
3. Crash

**Expected behavior**
Paths should be sanitized I guess

**Additional context**
Here are the logs:

```
server-romm-1  | INFO:     172.18.0.35:0 - "PATCH /platforms/NDS/roms/237 HTTP/1.0" 500 Internal Server Error
server-romm-1  | ERROR:    Exception in ASGI application
server-romm-1  | Traceback (most recent call last):
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
server-romm-1  |     result = await app(  # type: ignore[func-returns-value]
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
server-romm-1  |     return await self.app(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 276, in __call__
server-romm-1  |     await super().__call__(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
server-romm-1  |     await self.middleware_stack(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
server-romm-1  |     raise exc
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
server-romm-1  |     await self.app(scope, receive, _send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 92, in __call__
server-romm-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
server-romm-1  |     await self.app(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
server-romm-1  |     raise exc
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
server-romm-1  |     await self.app(scope, receive, sender)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
server-romm-1  |     raise e
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
server-romm-1  |     await self.app(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
server-romm-1  |     await route.handle(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
server-romm-1  |     await self.app(scope, receive, send)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
server-romm-1  |     response = await func(request)
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
server-romm-1  |     raw_response = await run_endpoint_function(
server-romm-1  |   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
server-romm-1  |     return await dependant.call(**values)
server-romm-1  |   File "/back/endpoints/rom.py", line 139, in updateRom
server-romm-1  |     fs.rename_rom(platform.fs_slug, db_rom.file_name, file_name)
server-romm-1  |   File "/back/utils/fs.py", line 288, in rename_rom
server-romm-1  |     os.rename(
server-romm-1  | FileNotFoundError: [Errno 2] No such file or directory: '/romm/library/roms/NDS/Kingdom_Hearts_368-2_Days' -> '/romm/library/roms/NDS/Kingdom Hearts 358/2 Days'
```

**Comment by zurdi15** [comment]
Oh wow nice catch, wondering how nobody detected this before. Working on a fix!

**Comment by zurdi15** [comment]
Sadly, after researching if a file name with slash character ('/') is possible in linux, it is not worth it the effort to make it possible (at this point I am not even sure this is possible at all), so RomM will do some validations before trying to rename, making slashes not allowed and making file name mandatory.

Sorry for not being the response you expected.

**Comment by ThibaultNocchi** [comment]
No problem, I didn't expect to have a slash in my filenames, as indeed it's not possible to have them in Linux. I just wanted the rename option to work, even without the slash. Thanks!
