### ISSUE TITLE
[Bug] List out of Range - Scanner

### ISSUE THREAD

**Issue by DunklerPhoenix** [zurdi15/romm#444]
**RomM version**
dev-latest

**Describe the bug**
Somehow the scanner get list out of range. I don't know if the naming is the problem (too many special signs?)

**Expected behavior**
Scan can handle files with strange names

**Screenshots**
Folder: /mnt/media/games/roms/gb
![Bildschirmfoto vom 2023-11-04 06-16-38](https://github.com/zurdi15/romm/assets/1261305/dfde1702-ecb8-498a-96b1-460332832f92)
![Bildschirmfoto vom 2023-11-04 06-24-53](https://github.com/zurdi15/romm/assets/1261305/08c2e4e2-8ddc-47ba-baed-d1ba3d0b874a)

**Additional context**

```
INFO:	  [RomM][2023-11-04 05:15:36]   Identified as Game Boy 🎮
05:15:36 [Job 5af83ae8-d4c9-4d6c-b4cf-194cc6b91a65]: exception raised while executing (endpoints.scan.scan_platforms)
Traceback (most recent call last):
  File "/backend/utils/fs.py", line 232, in get_roms
    fs_single_roms: list[str] = list(os.walk(roms_file_path))[0][2]
IndexError: list index out of range
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/backend/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/backend/lib/python3.10/site-packages/rq/job.py", line 1318, in _execute
    coro_result = loop.run_until_complete(result)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/backend/endpoints/scan.py", line 53, in scan_platforms
    fs_roms = fs.get_roms(scanned_platform.fs_slug)
  File "/backend/utils/fs.py", line 234, in get_roms
    raise RomsNotFoundException(p_slug) from exc
exceptions.fs_exceptions.RomsNotFoundException: Roms not found for platform gb. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure
```

DOCKER

```
version: '3.8'
services:
  romm:
    image: zurdi15/romm:dev-latest
    environment:
      - ROMM_DB_DRIVER=mariadb # mariadb | sqlite (default: sqlite)
      # [Optional] Only required if using MariaDB as the database
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=romm
      - DB_NAME=romm # Should match the MYSQL_DATABASE value in the mariadb container
      - DB_PASSWD=
      - IGDB_CLIENT_ID=
      - IGDB_CLIENT_SECRET=
      # [Optional - WIP] Use SteamGridDB as a source for covers
      - STEAMGRIDDB_API_KEY=
      # [Optional] Will enable user management and require authentication to access the interface (disabled by default)
      - ROMM_AUTH_ENABLED=true # default: false
      - ROMM_AUTH_SECRET_KEY= # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=admin # default: admin
      - ROMM_AUTH_PASSWORD=admin # default: admin
      # [Optional] Only required if authentication is enabled
      - ENABLE_EXPERIMENTAL_REDIS=true # default: false
      - REDIS_HOST=redis # default: localhost
      - REDIS_PORT=6379 # default: 6379
      #- REDIS_PASSWORD=<redis password> # [Optional] Support for secured redis
      # [Optional] Will enable asynchronous tasks (all disabled by default)
      - ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=true # Runs a quick scan on the library when a file is added or removed 
      - RESCAN_ON_FILESYSTEM_CHANGE_DELAY=5 # Delay in seconds before running the quick scan (default: 5)
      - ENABLE_SCHEDULED_RESCAN=true # Runs a quick scan on the library at a given time
      - SCHEDULED_RESCAN_CRON=0 3 * * * # Cron expression for the scheduled scan (default: 0 3 * * * - At 3:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB=true # Updates the Switch TitleDB database at a given time
      - SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON=0 4 * * * # Cron expression for the scheduled update (default: 0 4 * * * - At 4:00 AM every day)
      - ENABLE_SCHEDULED_UPDATE_MAME_XML=true # Updates the MAME XML database at a given time
      - SCHEDULED_UPDATE_MAME_XML_CRON=0 5 * * * # Cron expression for the scheduled update (default: 0 5 * * * - At 5:00 AM every day)
    volumes:
      - "/mnt/media/games/roms:/romm/library"
      - "/home/_files/romm/resources:/romm/resources" # [Optional] Path where roms metadata (covers) are stored
      - "/home/_files/romm/config.yml:/romm/config.yml" # [Optional] Path where config is stored
      - "/home/_files/romm/db:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
      - "/home/_files/romm/logs:/romm/logs" # [Optional] Path where logs are stored
```

**Comment by zurdi15** [comment]
The problem is that you need to mount your library until `games` instead of `roms`, like this:

`- "/mnt/media/games:/romm/library"`

**Comment by DunklerPhoenix** [comment]
Oh. I'm sorry. Didn't really realize that ^^'
