### ISSUE TITLE
[Bug] database migration fails on latest master branch when sqlite is used

### ISSUE THREAD

**Issue by psych0d0g** [zurdi15/romm#461]
**RomM version**
selfbuild docker from master branch

**Describe the bug**
sqlite alembic migrations fail with a stacktrace related to https://github.com/zurdi15/romm/blob/master/backend/alembic/versions/0009_models_refactor.py#L35
```
INFO:     [RomM][alembic.runtime.migration] Context impl SQLiteImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
INFO:     [RomM][alembic.runtime.migration] Running upgrade 2.0.0 -> 0009_models_refactor, empty message
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/alembic/operations/batch.py", line 689, in drop_constraint
    const = self.named_constraints.pop(const.name)
KeyError: 'PRIMARY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/backend/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/backend/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/backend/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/backend/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/backend/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/backend/alembic/env.py", line 82, in <module>
    run_migrations_online()
  File "/backend/alembic/env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/backend/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/backend/lib/python3.10/site-packages/alembic/runtime/migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "/backend/alembic/versions/0009_models_refactor.py", line 20, in upgrade
    with op.batch_alter_table("platforms", schema=None) as batch_op:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/backend/lib/python3.10/site-packages/alembic/operations/base.py", line 383, in batch_alter_table
    impl.flush()
  File "/backend/lib/python3.10/site-packages/alembic/operations/batch.py", line 159, in flush
    fn(*arg, **kw)
  File "/backend/lib/python3.10/site-packages/alembic/operations/batch.py", line 700, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'PRIMARY'
ERROR:    [init][2023-11-14 07:23:44] Something went horribly wrong with our database
```

**To Reproduce**
1. install romm dev-2.1.1-rc.1
2. upgrade to master branch

**Expected behavior**
database should be migrated

**Screenshots**

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by zurdi15** [comment]
I need to test this, I didn't test sqlite the last couple of releases :confused:

**Comment by gantoine** [comment]
Seems it's trying to drop the primary key constraint from the platform table, but it doesn't exist in the first place. If you're up for it, you might be able to `exec` into the container, edit that migration file to comment out that line and re-run the migrations.

**Comment by psych0d0g** [comment]
> Seems it's trying to drop the primary key constraint from the platform table, but it doesn't exist in the first place. If you're up for it, you might be able to `exec` into the container, edit that migration file to comment out that line and re-run the migrations.

cant change anything inside my running deployment, sorry, the container is running as readonly rootfs for me, so no quick way currently, i could change some things around maybe, but thats not a fast route forward

**Comment by gantoine** [comment]
Can you access the db directly using something like dbeaver? I'm curious to see know a) what alembic_version is in the table and b) why the platform table has no primary key. SQLite should support primary keys AFAIK.

**Comment by rursache** [comment]
having the same issue

**Comment by gantoine** [comment]
A fix for this was just merged in and will be available in the next release.
