### ISSUE TITLE
[Bug] Scan Crashes - Task exception was never retrieved

### ISSUE THREAD

**Issue by hevel86** [zurdi15/romm#475]
**RomM version**
2.1.0

**Describe the bug**
The scanner crashes when it arrives at the Playstation section.  I don't know if Playstation is the cause but it's 100% correlated and consistent.

**To Reproduce**
1. Simply click the "Scan" button in the web UI
2. Wait and observe the docker logs (I used Portainer)

**Expected behavior**
Finish the scan without error out or gracefully handling the error.

**Screenshots**
![brave_luAsx9Pe3R](https://github.com/zurdi15/romm/assets/2089595/ec500cf5-0e0d-4bb6-8704-6efb367e7f46)

**Code block of error for easy copy-paste**
```
INFO:	  [RomM][2023-11-27 21:31:16]   Identified as PlayStation 🎮
INFO:	  [RomM][2023-11-27 21:31:20] 	 · wget-log
Task exception was never retrieved
future: <Task finished name='Task-18' coro=<AsyncServer._handle_event_internal() done, defined at /backend/lib/python3.10/site-packages/socketio/asyncio_server.py:522> exception=AttributeError("'NoneType' object has no attribute 'group'")>
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/backend/lib/python3.10/site-packages/socketio/asyncio_server.py", line 558, in _trigger_event
    ret = await handler(*args)
  File "/backend/endpoints/scan.py", line 100, in scan_handler
    await scan_platforms(platform_slugs, complete_rescan, selected_roms)
  File "/backend/endpoints/scan.py", line 59, in scan_platforms
    scanned_rom = await fastapi.scan_rom(scanned_platform, fs_rom)
  File "/backend/utils/fastapi.py", line 72, in scan_rom
    "file_extension": get_file_extension(rom_attrs),
  File "/backend/utils/__init__.py", line 109, in get_file_extension
    re.search(EXTENSION_REGEX, rom["file_name"]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
172.19.0.1 - - [27/Nov/2023:21:31:20 +0000] "GET /assets/platforms/ps.ico HTTP/1.1" 200 270622 "http://192.168.1.10:86/library/scan" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

**Additional Info:**
 - Server OS: Ubuntu 22.04.3 LTS x86_64
 - Docker: 24.0.7, build afdd53b
 - Browser: Brave or Firefox (to access web UI)

**Additional context**
Created using docker-compose in a stack with MariaDB

**Comment by hevel86** [comment]
> You have a bad file in there called `wget_log`, remove it and the scan should continue working as expected.

Ah, ok. I wasn't understanding the folder structure and output like I needed.  Thanks!
