### ISSUE TITLE
[Bug] Scan fails after an indeterminant period of time

### ISSUE THREAD

**Issue by adam-fox** [zurdi15/romm#518]
**RomM version**
dev-2.1.1-rc

**Describe the bug**
Scan fails after an indeterminant period of time.

**To Reproduce**
1. Go to 'Scan'
2. Click on 'Scan'

**Expected behavior**
Scan runs and completes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Unraid

`10:44:15 [Job 042f9f65-fa46-4520-9209-5820aee82adc]: exception raised while executing (endpoints.scan.scan_platforms)
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/backend/lib/python3.10/site-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/backend/lib/python3.10/site-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/backend/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/backend/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: _ssl.c:990: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/backend/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/backend/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='images.igdb.com', port=443): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
    rv = job.perform()
  File "/backend/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
    self._result = self._execute()
  File "/backend/lib/python3.10/site-packages/rq/job.py", line 1318, in _execute
    coro_result = loop.run_until_complete(result)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/backend/endpoints/scan.py", line 59, in scan_platforms
    scanned_rom = await fastapi.scan_rom(scanned_platform, fs_rom)
  File "/backend/utils/fastapi.py", line 105, in scan_rom
    fs.get_cover(
  File "/backend/utils/fs.py", line 80, in get_cover
    _store_cover(p_slug, r_name, url_cover, "small")
  File "/backend/utils/fs.py", line 54, in _store_cover
    res = requests.get(
  File "/backend/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/backend/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/backend/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/backend/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/backend/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='images.igdb.com', port=443): Read timed out. (read timeout=120)

10:44:15 Cleaning registries for queue: high
10:44:15 Cleaning registries for queue: default
10:44:15 Cleaning registries for queue: low`

**Comment by gantoine** [comment]
Seems the fetch for the cover image is timing out after 120s, which kills the scan

```
File "/backend/utils/fs.py", line 80, in get_cover
_store_cover(p_slug, r_name, url_cover, "small")
File "/backend/utils/fs.py", line 54, in _store_cover
res = requests.get(
```

**Comment by adam-fox** [comment]
hmm... any reason it would be failing and is it possible to just skip that particular item instead of killing the scan?

**Comment by gantoine** [comment]
Yeah that's not a bad idea, i'll see what I can do really quick...
