### ISSUE TITLE
[Bug] Data too long for column 'file_extension' at row 1 

### ISSUE THREAD

**Issue by daedric7** [zurdi15/romm#531]
**RomM version**
 image: zurdi15/romm:dev-latest

**Describe the bug**
Error in the logs while importing:

```
romm     | INFO:          [RomM][2023-12-30 14:21:27]      Identified as Romance of the Three Kingdoms II 👾
romm     | 14:21:28 [Job 55efa4b9-69a7-4699-b749-4501bfe5fdb0]: exception raised while executing (endpoints.scan.scan_platforms)
romm     | Traceback (most recent call last):
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
romm     |     self.dialect.do_execute(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
romm     |     cursor.execute(statement, parameters)
romm     |   File "/backend/lib/python3.10/site-packages/mariadb/cursors.py", line 314, in execute
romm     |     self._execute_binary()
romm     | mariadb.DataError: Data too long for column 'file_extension' at row 1
romm     |
romm     | The above exception was the direct cause of the following exception:
romm     |
romm     | Traceback (most recent call last):
romm     |   File "/backend/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
romm     |     rv = job.perform()
romm     |   File "/backend/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
romm     |     self._result = self._execute()
romm     |   File "/backend/lib/python3.10/site-packages/rq/job.py", line 1318, in _execute
romm     |     coro_result = loop.run_until_complete(result)
romm     |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
romm     |     return future.result()
romm     |   File "/backend/endpoints/scan.py", line 78, in scan_platforms
romm     |     _new_rom = dbh.add_rom(scanned_rom)
romm     |   File "/backend/handler/db_handler.py", line 26, in wrapper
romm     |     with args[0].session.begin() as s:
romm     |   File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
romm     |     next(self.gen)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1755, in _maker_context_manager
romm     |     with self.begin():
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 146, in __exit__
romm     |     with util.safe_reraise():
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
romm     |     raise exc_value.with_traceback(exc_tb)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 144, in __exit__
romm     |     self.commit()
romm     |   File "<string>", line 2, in commit
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
romm     |     ret_value = fn(self, *arg, **kw)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
romm     |     self._prepare_impl()
romm     |   File "<string>", line 2, in _prepare_impl
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
romm     |     ret_value = fn(self, *arg, **kw)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
romm     |     self.session.flush()
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
romm     |     self._flush(objects)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
romm     |     with util.safe_reraise():
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
romm     |     raise exc_value.with_traceback(exc_tb)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
romm     |     flush_context.execute()
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
romm     |     rec.execute(self)
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
romm     |     util.preloaded.orm_persistence.save_obj(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
romm     |     _emit_insert_statements(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1226, in _emit_insert_statements
romm     |     result = connection.execute(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
romm     |     return meth(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
romm     |     return connection._execute_clauseelement(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
romm     |     ret = self._execute_context(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
romm     |     return self._exec_single_context(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
romm     |     self._handle_dbapi_exception(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
romm     |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
romm     |     self.dialect.do_execute(
romm     |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
romm     |     cursor.execute(statement, parameters)
romm     |   File "/backend/lib/python3.10/site-packages/mariadb/cursors.py", line 314, in execute
romm     |     self._execute_binary()
romm     | sqlalchemy.exc.DataError: (mariadb.DataError) Data too long for column 'file_extension' at row 1
romm     | [SQL: INSERT INTO roms (igdb_id, sgdb_id, platform_slug, p_name, p_igdb_id, p_sgdb_id, file_name, file_name_no_tags, file_extension, file_path, file_size, file_size_units, name, slug, summary, path_cover_s, path_cover_l, url_cover, revision, regions, languages, tags, multi, files, url_screenshots, path_screenshots) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
romm     | [parameters: (7026, None, 'snes', '', '', '', '2.noheader.zip', '2', 'noheader.zip', 'roms/snes', 1.35, 'MB', 'Romance of the Three Kingdoms II', 'romance-of-the-three-kingdoms-ii', 'The player takes control of a master, a general capable of commanding as many states as he can acquire, and, if successful, unifies China. As many as ... (353 characters truncated) ... ssible. After the completion of any scenario but number five the game will automatically advance to the next. You may start the game at any scenario.', 'snes/Romance%20of%20the%20Three%20Kingdoms%20II/cover/small.png?timestamp=1703946087.96558', 'snes/Romance%20of%20the%20Three%20Kingdoms%20II/cover/big.png?timestamp=1703946087.965599', 'https://images.igdb.com/igdb/image/upload/t_thumb/co5p7z.jpg', '', '[]', '[]', '[]', 0, '[]', '["https://images.igdb.com/igdb/image/upload/t_original/gzzcskbm8htkx30croyy.jpg", "https://images.igdb.com/igdb/image/upload/t_original/s31qrtnwvmvvp ... (107 characters truncated) ... ges.igdb.com/igdb/image/upload/t_original/vf6swqoi9m82fmicgerh.jpg", "https://images.igdb.com/igdb/image/upload/t_original/jdbsmkteedjo7h0xxozt.jpg"]', '["snes/Romance%20of%20the%20Three%20Kingdoms%20II/screenshots/0.jpg", "snes/Romance%20of%20the%20Three%20Kingdoms%20II/screenshots/1.jpg", "snes/Roma ... (47 characters truncated) ... ots/2.jpg", "snes/Romance%20of%20the%20Three%20Kingdoms%20II/screenshots/3.jpg", "snes/Romance%20of%20the%20Three%20Kingdoms%20II/screenshots/4.jpg"]')]
romm     | (Background on this error at: https://sqlalche.me/e/20/9h9h)
```

**Additional context**
This seems to be a exact copy of [[Bug] mariadb.DataError: Data too long for column 'file_extension' at row 1 #170](https://github.com/zurdi15/romm/issues/170#issue-1667499745) , but this one happened today.

**Comment by gantoine** [comment]
What's the full name of the file that ends with `2.noheader.zip`? It's trying to scan and save it but the file extension is too long.

**Comment by daedric7** [comment]
Must be this one:

```
/share/roms# find | grep '2.noheader.zip'
./snes/2.noheader.zip
```
