### ISSUE TITLE
[Bug] DB Migration fails after upgrade from 2.1.0 to 2.2.0

### ISSUE THREAD

**Issue by DarkVirtue** [zurdi15/romm#539]
**RomM version**
2.2.0 (Docker)

**Describe the bug**
RomM fails to start with the following error:
```
romm  | ESC[92mINFOESC[0m:ESC[94m         [RomM]ESC[96m[2024-01-01 15:25:47] ESC[0mConfig loaded successfully from /romm/config.yml
romm  | INFO:     [RomM][alembic.runtime.migration] Context impl MariaDBImpl.
romm  | INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
romm  | INFO:     [RomM][alembic.runtime.migration] Running upgrade 2.0.0 -> 0009_models_refactor, empty message
romm  | Moved primary key to slug column on platforms table
romm  | Traceback (most recent call last):
romm  |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
romm  |     self.dialect.do_execute(
romm  |   File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
romm  |     cursor.execute(statement, parameters)
romm  |   File "/backend/lib/python3.10/site-packages/mariadb/cursors.py", line 311, in execute
romm  |     self._readresponse()
romm  | mariadb.OperationalError: Unknown column 'r_igdb_id' in 'roms'
```

**To Reproduce**
1. Set up RomM 2.1.0 or earlier
2. Use MariaDB/MySQL backend
3. Upgrade to 2.2.0
4. Start the container

**Expected behavior**
The DB should be migrated cleanly, creating missing columns before trying to alter them.

**Additional context**

**Comment by gantoine** [comment]
Any chance you were using one of the `dev-`/`rc-` containers between 2.1.0 and 2.2.20? There are a couple ways to fix this without having to wipe your DB but they can be a bit tricky.

**Comment by DarkVirtue** [comment]
I was using the `latest` tag before

**Comment by gantoine** [comment]
Can you access the D directly with something like dbeaver, or another DB viewer?

**Comment by DarkVirtue** [comment]
I don't have any of those set up, but I'm fairly comfortable in the MariaDB CLI. What would you like me to do?

**Comment by gantoine** [comment]
Could you post a screenshot of the current structure of the roms table? Like this:

![Uploading Screenshot 2024-01-01 at 11.56.29 AM.png…]()

**Comment by DarkVirtue** [comment]
```MariaDB [romm]> describe roms;
+-------------------+---------------+------+-----+---------+----------------+
| Field             | Type          | Null | Key | Default | Extra          |
+-------------------+---------------+------+-----+---------+----------------+
| id                | int(11)       | NO   | PRI | NULL    | auto_increment |
| igdb_id           | varchar(10)   | YES  |     | NULL    |                |
| p_igdb_id         | varchar(10)   | YES  |     | NULL    |                |
| sgdb_id           | varchar(10)   | YES  |     | NULL    |                |
| p_sgdb_id         | varchar(10)   | YES  |     | NULL    |                |
| platform_slug     | varchar(50)   | NO   |     | NULL    |                |
| p_name            | varchar(150)  | YES  |     | NULL    |                |
| file_name         | varchar(450)  | NO   |     | NULL    |                |
| file_name_no_tags | varchar(450)  | NO   |     | NULL    |                |
| file_extension    | varchar(10)   | NO   |     | NULL    |                |
| file_path         | varchar(1000) | NO   |     | NULL    |                |
| file_size         | float         | NO   |     | NULL    |                |
| file_size_units   | varchar(10)   | NO   |     | NULL    |                |
| name              | varchar(350)  | YES  |     | NULL    |                |
| slug              | varchar(400)  | YES  |     | NULL    |                |
| summary           | text          | YES  |     | NULL    |                |
| path_cover_s      | text          | YES  |     | NULL    |                |
| path_cover_l      | text          | YES  |     | NULL    |                |
| has_cover         | tinyint(1)    | YES  |     | NULL    |                |
| region            | varchar(20)   | YES  |     | NULL    |                |
| revision          | varchar(20)   | YES  |     | NULL    |                |
| tags              | longtext      | YES  |     | NULL    |                |
| multi             | tinyint(1)    | YES  |     | NULL    |                |
| files             | longtext      | YES  |     | NULL    |                |
| url_cover         | text          | YES  |     | NULL    |                |
| url_screenshots   | longtext      | YES  |     | '[]'    |                |
| path_screenshots  | longtext      | YES  |     | '[]'    |                |
+-------------------+---------------+------+-----+---------+----------------+
27 rows in set (0.002 sec)
```

**Comment by gantoine** [comment]
Seems 0009 already ran, probably in an earlier launch of the server. Can you update the entry in `alembic_version` to `0009_models_refactor`?

**Comment by DarkVirtue** [comment]
My instance is up and running without issue on version 2.2.0 now. Thanks a ton!
