### ISSUE TITLE
[Bug] UNIQUE constraint failed: platforms.fs_slug') when re-scanning a platform after updating config file

### ISSUE THREAD

**Issue by bfenty** [zurdi15/romm#567]
**RomM version**
docker:latest

**Describe the bug**
Romm isn't scanning a folder that's already been scanned if it was previously unrecognized and has since been mapped to the correct slug via config file.

**To Reproduce**

1. Have scanned the folder as a platform that is not recognized
2. update config file to map folder name to correct slug
3. run another update
4. see error

**Expected behavior**
I would expect it to scan the folder.

**Log test**
```
Task exception was never retrieved
future: <Task finished name='Task-48' coro=<AsyncServer._handle_event_internal() done, defined at /backend/lib/python3.10/site-packages/socketio/asyncio_server.py:522> exception=IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: platforms.fs_slug')>
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: platforms.fs_slug


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/backend/lib/python3.10/site-packages/socketio/asyncio_server.py", line 558, in _trigger_event
    ret = await handler(*args)
  File "/backend/endpoints/scan.py", line 120, in scan_handler
    await scan_platforms(platform_slugs, complete_rescan, rescan_unidentified, selected_roms)
  File "/backend/endpoints/scan.py", line 47, in scan_platforms
    _new_platform = dbh.add_platform(scanned_platform)
  File "/backend/handler/db_handler.py", line 26, in wrapper
    with args[0].session.begin() as s:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1755, in _maker_context_manager
    with self.begin():
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 146, in __exit__
    with util.safe_reraise():
  File "/backend/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/util.py", line 144, in __exit__
    self.commit()
  File "<string>", line 2, in commit
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1256, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1231, in _prepare_impl
    self.session.flush()
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4312, in flush
    self._flush(objects)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4447, in _flush
    with util.safe_reraise():
  File "/backend/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 4408, in _flush
    flush_context.execute()
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1043, in _emit_insert_statements
    result = connection.execute(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
    ret = self._execute_context(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: platforms.fs_slug
[SQL: INSERT INTO platforms (slug, fs_slug, name, igdb_id, sgdb_id, logo_path, n_roms) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('ps', 'PSX', 'PlayStation', 7, None, 'default/default/cover/small.png', 0)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

```

**Comment by gantoine** [comment]
Ugh yeah I know what's going on here, I'll have a fix in the code but you'll need to delete the bad entry from your DB to get running again. That or remove all the Roms via the UI for that old/bad platform, which should purge the platform next scan.

**Comment by bfenty** [comment]
Hope can you remove them via the ui?

**Comment by gantoine** [comment]
Find any roms that belong to the old platform and delete the entries (without removing the files), then setup your library right and run a scan.

**Comment by bfenty** [comment]
Do you have to do that individually? It's a lot of files..

Is it possible for me to edit the db directly? I see the container creates it, just not sure how to go about accessing it. It's sqlite?

**Comment by zurdi15** [comment]
If it helps, in the gallery you can use `control` and/or `shift` keys to bulk select roms and delete them

**Comment by bfenty** [comment]
> If it helps, in the gallery you can use `control` and/or `shift` keys to bulk select roms and delete them

That would likely help, yes.

> Yeah most db tools should be able to connect, or you can do it via the sqlite CLI (though you'll need to install it within the romm container).

If the sqlite db is in a bind mount, couldn't you do it from the host OS?

**Comment by zurdi15** [comment]
> If the sqlite db is in a bind mount, couldn't you do it from the host OS?

Yeah, you should be able to open the sqlite file from the host
