### ISSUE TITLE
[Bug] Task exceeded maximum timeout value

### ISSUE THREAD

**Issue by daedric7** [zurdi15/romm#573]
**RomM version**
RomM dev-2.2.0-rc.1

**Describe the bug**
Scan fails after a timeout to https://api.igdb.com/v4/games/

**To Reproduce**
Have a large rom list, scan it.

```
romm  | INFO:     [RomM][2024-01-04 22:57:20]    · Master Mega Man (WonderBoy in ML Hack).zip
romm  | ERROR:    [RomM][2024-01-04 22:57:20] 400 Client Error: Bad Request for url: https://api.igdb.com/v4/games/
romm  | 22:57:20 [Job 2fa9b814-052f-437a-a735-49ab4cfc4715]: exception raised while executing (endpoints.scan.scan_platforms)
romm  | Traceback (most recent call last):
romm  |   File "/backend/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
romm  |     rv = job.perform()
romm  |   File "/backend/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
romm  |     self._result = self._execute()
romm  |   File "/backend/lib/python3.10/site-packages/rq/job.py", line 1318, in _execute
romm  |     coro_result = loop.run_until_complete(result)
romm  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
romm  |     return future.result()
romm  |   File "/backend/endpoints/scan.py", line 74, in scan_platforms
romm  |     scanned_rom = await scan_rom(scanned_platform, fs_rom)
romm  |   File "/backend/utils/fastapi.py", line 87, in scan_rom
romm  |     else await igdbh.get_rom(rom_attrs["file_name"], platform.igdb_id)
romm  |   File "/backend/handler/igdb_handler.py", line 287, in get_rom
romm  |     or self._search_rom(
romm  |   File "/backend/handler/igdb_handler.py", line 118, in _search_rom
romm  |     roms = self._request(
romm  |   File "/backend/handler/igdb_handler.py", line 87, in _request
romm  |     res = requests.post(url, data, headers=self.headers, timeout=timeout)
romm  |   File "/backend/lib/python3.10/site-packages/requests/api.py", line 115, in post
romm  |     return request("post", url, data=data, json=json, **kwargs)
romm  |   File "/backend/lib/python3.10/site-packages/requests/api.py", line 59, in request
romm  |     return session.request(method=method, url=url, **kwargs)
romm  |   File "/backend/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
romm  |     resp = self.send(prep, **send_kwargs)
romm  |   File "/backend/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
romm  |     r = adapter.send(request, **kwargs)
romm  |   File "/backend/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
romm  |     resp = conn.urlopen(
romm  |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
romm  |     response = self._make_request(
romm  |   File "/backend/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
romm  |     response = conn.getresponse()
romm  |   File "/backend/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
romm  |     httplib_response = super().getresponse()
romm  |   File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
romm  |     response.begin()
romm  |   File "/usr/lib/python3.10/http/client.py", line 318, in begin
romm  |     version, status, reason = self._read_status()
romm  |   File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
romm  |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
romm  |   File "/usr/lib/python3.10/socket.py", line 705, in readinto
romm  |     return self._sock.recv_into(b)
romm  |   File "/usr/lib/python3.10/ssl.py", line 1307, in recv_into
romm  |     return self.read(nbytes, buffer)
romm  |   File "/usr/lib/python3.10/ssl.py", line 1163, in read
romm  |     return self._sslobj.read(len, buffer)
romm  |   File "/backend/lib/python3.10/site-packages/rq/timeouts.py", line 63, in handle_death_penalty
romm  |     raise self._exception('Task exceeded maximum timeout value ({0} seconds)'.format(self._timeout))
romm  | rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (14400 seconds)
```

**Comment by zurdi15** [comment]
How large are we talking about?

In any case, we should control the ``timeout`` against igdb because sometimes it can be a problem

**Comment by daedric7** [comment]
> How large are we talking about?
> 
> In any case, we should control the `timeout` against igdb because sometimes it can be a problem

Nothing... extraordinary!

 ```
find | wc -l
43164
```

The timeout being 240 minutes is perhaps... too large. But this is not the issue i think, it's the fact that it stops and doesn't attempt to continue. This timeout might be ephemeral, the next attempt might succeed.

**Comment by gantoine** [comment]
> 43164

😱

**Comment by CygnusHyoga** [comment]
I have a huge library too and it doesn't finish because of the 4 hour timeout. Could the timout configuration be added by environment variable? or directly disable the timeout? Thank you! I love the concept of RomM, it's wonderful!
