### ISSUE TITLE
[Bug] DB-Migration  "Could not locate column in row for column 'keys'"

### ISSUE THREAD

**Issue by Fabaderheld** [zurdi15/romm#697]
**RomM version**
3.0.1-rc.2

**Describe the bug**
Database migration fails with **"Could not locate column in row for column 'keys'"**

in detail
```
9:M 13 Mar 2024 10:51:15.644 * Ready to accept connections tcp
INFO:     [RomM][alembic.runtime.migration] Context impl MariaDBImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
INFO:     [RomM][alembic.runtime.migration] Running upgrade 0013_upgrade_file_extension -> 0014_asset_files, empty message
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 202, in _key_not_found
    self._key_fallback(key, None)
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 823, in _key_fallback
    raise exc.NoSuchColumnError(
sqlalchemy.exc.NoSuchColumnError: Could not locate column in row for column 'keys'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/backend/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/backend/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/backend/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/backend/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/backend/alembic/env.py", line 86, in <module>
    run_migrations_online()
  File "/backend/alembic/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/backend/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/backend/lib/python3.10/site-packages/alembic/runtime/migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "/backend/alembic/versions/0014_asset_files.py", line 77, in upgrade
    migrate_to_mysql()
  File "/backend/alembic/versions/0014_asset_files.py", line 69, in migrate_to_mysql
    insert_query = f"INSERT INTO {table_name} VALUES ({', '.join([':%s' % key for key in row.keys()])})"
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 66, in sqlalchemy.cyextension.resultproxy.BaseRow.__getattr__
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 63, in sqlalchemy.cyextension.resultproxy.BaseRow._get_by_key_impl
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 204, in _key_not_found
    raise AttributeError(ke.args[0]) from ke
AttributeError: Could not locate column in row for column 'keys'
ERROR:    [init][2024-03-13 10:51:16] Something went horribly wrong with our database
```

**To Reproduce**
Start new V3 container  to trigger the db migration

**Expected behavior**
To finish DB migration

**Additional context**
Used the 3.0.1-rc.2 since there was another issue with 3.0 which did not occur with 3.0.1-rc.2.

**Comment by gantoine** [comment]
damn it i was worried this would happen. ok we're going to fix this in an RC3 👍🏼
