### ISSUE TITLE
[Bug] Compose

### ISSUE THREAD

**Issue by XargonWan** [zurdi15/romm#74]
**Describe the bug**
When I start romm via docker compose in sqlite mode I get this errors:
```
[+] Running 1/1
 ⠿ Container romm  Recreated                                                                                                                                 0.5s
Attaching to romm
romm  | INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
romm  | INFO:     Started parent process [10]
romm  | Process SpawnProcess-3:
romm  | Traceback (most recent call last):
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
romm  |     self.run()
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
romm  |     self._target(*self._args, **self._kwargs)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
romm  |     target(sockets=sockets)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
romm  |     return asyncio.run(self.serve(sockets=sockets))
romm  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
romm  |     return loop.run_until_complete(main)
romm  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
romm  |     return future.result()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
romm  |     config.load()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 477, in load
romm  |     self.loaded_app = import_from_string(self.app)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
romm  |     module = importlib.import_module(module_str)
romm  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
romm  |     return _bootstrap._gcd_import(name[level:], package, level)
romm  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
romm  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
romm  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
romm  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
romm  |   File "/back/./main.py", line 5, in <module>
romm  |     from handler.igdb_handler import IGDBHandler
romm  |   File "/back/./handler/igdb_handler.py", line 8, in <module>
romm  |     from config.config import CLIENT_ID, CLIENT_SECRET
romm  |   File "/back/./config/config.py", line 28, in <module>
romm  |     DB_PORT: int = int(os.getenv('DB_PORT'))
romm  | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
romm  | Process SpawnProcess-1:
romm  | Traceback (most recent call last):
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
romm  |     self.run()
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
romm  |     self._target(*self._args, **self._kwargs)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
romm  |     target(sockets=sockets)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
romm  |     return asyncio.run(self.serve(sockets=sockets))
romm  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
romm  |     return loop.run_until_complete(main)
romm  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
romm  |     return future.result()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
romm  |     config.load()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 477, in load
romm  |     self.loaded_app = import_from_string(self.app)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
romm  |     module = importlib.import_module(module_str)
romm  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
romm  |     return _bootstrap._gcd_import(name[level:], package, level)
romm  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
romm  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
romm  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
romm  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
romm  |   File "/back/./main.py", line 5, in <module>
romm  |     from handler.igdb_handler import IGDBHandler
romm  |   File "/back/./handler/igdb_handler.py", line 8, in <module>
romm  |     from config.config import CLIENT_ID, CLIENT_SECRET
romm  |   File "/back/./config/config.py", line 28, in <module>
romm  |     DB_PORT: int = int(os.getenv('DB_PORT'))
romm  | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
romm  | Process SpawnProcess-4:
romm  | Traceback (most recent call last):
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
romm  |     self.run()
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
romm  |     self._target(*self._args, **self._kwargs)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
romm  |     target(sockets=sockets)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
romm  |     return asyncio.run(self.serve(sockets=sockets))
romm  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
romm  |     return loop.run_until_complete(main)
romm  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
romm  |     return future.result()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
romm  |     config.load()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 477, in load
romm  |     self.loaded_app = import_from_string(self.app)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
romm  |     module = importlib.import_module(module_str)
romm  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
romm  |     return _bootstrap._gcd_import(name[level:], package, level)
romm  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
romm  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
romm  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
romm  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
romm  |   File "/back/./main.py", line 5, in <module>
romm  |     from handler.igdb_handler import IGDBHandler
romm  |   File "/back/./handler/igdb_handler.py", line 8, in <module>
romm  |     from config.config import CLIENT_ID, CLIENT_SECRET
romm  |   File "/back/./config/config.py", line 28, in <module>
romm  |     DB_PORT: int = int(os.getenv('DB_PORT'))
romm  | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
romm  | Process SpawnProcess-2:
romm  | Traceback (most recent call last):
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
romm  |     self.run()
romm  |   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
romm  |     self._target(*self._args, **self._kwargs)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
romm  |     target(sockets=sockets)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
romm  |     return asyncio.run(self.serve(sockets=sockets))
romm  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
romm  |     return loop.run_until_complete(main)
romm  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
romm  |     return future.result()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
romm  |     config.load()
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 477, in load
romm  |     self.loaded_app = import_from_string(self.app)
romm  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
romm  |     module = importlib.import_module(module_str)
romm  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
romm  |     return _bootstrap._gcd_import(name[level:], package, level)
romm  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
romm  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
romm  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
romm  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
romm  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
romm  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
romm  |   File "/back/./main.py", line 5, in <module>
romm  |     from handler.igdb_handler import IGDBHandler
romm  |   File "/back/./handler/igdb_handler.py", line 8, in <module>
romm  |     from config.config import CLIENT_ID, CLIENT_SECRET
romm  |   File "/back/./config/config.py", line 28, in <module>
romm  |     DB_PORT: int = int(os.getenv('DB_PORT'))
romm  | TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
If I try to scan me roms folder I get " Couldn't complete scan. Something went wrong...".

**To Reproduce**
1. set client_id and _secret
2. set the volume on the right rom library location
3. changed the forwarded port from 80 to 45107 (tried multiple)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS (Linux Debian)
 - Browser Vivaldi, Chrome
 - Version latest on 29/03/2023

**Comment by XargonWan** [comment]
Working, thanks a lot!

**Comment by javijuji** [comment]
I am still getting the same error. Could you share your compose file?

**Comment by XargonWan** [comment]
> I am still getting the same error. Could you share your compose file?

```yml
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - CLIENT_ID=foo
      - CLIENT_SECRET=bar
      - STEAMGRIDDB_API_KEY=WIP
      - PUID=1000
      - PGID=1000
      - TZ=Time/Zone
    volumes:
      - '/foo/bar:/library'
    ports:
      - '45107:80'
    restart: "unless-stopped"
```

Here you are
